step: "Merge metadata"
description: "Merge metadata of multiple sources"
function file: "shared/merge_metadata"
function: "combine_index_files"

basic_data_path: "data/pdbbind"
igmodel_initial_cleanup_input_path: "${{ basic_data_path }}/core/raw/for_use"
igmodel_initial_cleanup_output_path: "${{ basic_data_path }}/core/stage_1_cleaned"
input_path: "${{ igmodel_initial_cleanup_input_path }}"
output_paths: 
  data_path: "${{ igmodel_initial_cleanup_output_path }}/stage_1_merged"
  metadata_path: "${{ basic_data_path }}/metadata/generated/core_metadata"

input:
  input_paths:
    "{input_path}/PDBbind_v2019_plain_text_index/plain-text-index/index/INDEX_refined_data.2019, {input_path}/PDBbind_v2019_plain_text_index/plain-text-index/index/INDEX_general_PL_data.2019"
  output_path: "${{ output_paths.metadata_path }}/combined_metadata.txt"
