step: "Merge folders"
description: "Merge given folders into one folder"
function file: "shared/folders_management"
function: "merge_folders_with_log"

basic_data_path: "data/pdbbind"
igmodel_initial_cleanup_input_path: "${{ basic_data_path }}/core/raw/for_use"
igmodel_initial_cleanup_output_path: "${{ basic_data_path }}/core/stage_1_cleaned"
input_path: "${{ igmodel_initial_cleanup_input_path }}"
output_paths: 
  data_path: "${{ igmodel_initial_cleanup_output_path }}/stage_1_merged"
  metadata_path: "${{ basic_data_path }}/metadata/generated/core_metadata"

input:
  input_paths:
    "{igmodel_initial_cleanup_input_path}/pdbbind_v2019_other_PL, 
    {igmodel_initial_cleanup_input_path}/pdbbind_v2019_refined"  
  output_path: "${{ output_paths.data_path }}"
return: "log" 